/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package konnik.json

import kotlin.test.Test
import kotlin.test.assertEquals


val TESTJSON =     """
    {"hej"   : "apa\t"
    , "x" : [1,2,3,false,true,null],
    "y" : null
    }
    """



class ParserKtTest {
    @Test fun `true`() {
        val result = json.runParser("true")
        assertEquals(JsonValue.Bool(true), result)
    }

    @Test fun `false`() {
        val result = json.runParser("false")
        assertEquals(JsonValue.Bool(false), result)
    }

    @Test fun `null`() {
        val result = json.runParser("null")
        assertEquals(JsonValue.Null, result)
    }

    @Test fun `string with unicode`() {
        val result = json.runParser("""
        "Unicode char: \u00A9"
        """)
        assertEquals(JsonValue.Str("Unicode char: ©"), result)
    }

    @Test fun `empty array`() {
        val result = json.runParser("[]")
        assertEquals(JsonValue.Array(emptyList()), result)
    }

    @Test fun `array with values`() {
        val result = json.runParser("""
            [true,false,["string with comma,",42]]
            """)
        assertEquals(JsonValue.Array(listOf(
            JsonValue.Bool(true),
            JsonValue.Bool(false),
            JsonValue.Array(listOf(
                JsonValue.Str("string with comma,"),
                JsonValue.Num(42.0)
            )))),
            result
        )
    }

}
